# Generated by Django 3.2.5 on 2021-07-20 07:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_hr_management',
            fields=[
                ('Business_Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Business_Name', models.TextField()),
                ('Phone_Number', models.TextField()),
                ('Industry', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Director_First_Name', models.TextField()),
                ('Directors_Last_Name', models.TextField()),
                ('Directors_Other_Name', models.TextField()),
                ('Directors_Phone_Number', models.TextField()),
                ('Director_Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('First_name', models.TextField()),
                ('Last_name', models.TextField()),
                ('Other_Names', models.TextField()),
                ('Id_Number', models.TextField()),
                ('Phone_Number', models.TextField()),
                ('Post', models.TextField()),
                ('Company_Position', models.TextField()),
                ('Business_hr_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.business_hr_management')),
            ],
        ),
        migrations.CreateModel(
            name='Work_day',
            fields=[
                ('Work_day_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Business_hr_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.business_hr_management')),
                ('Employee', models.ManyToManyField(to='hr_management.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Task', models.TextField()),
                ('State', models.BooleanField()),
                ('From', models.TextField()),
                ('Date', models.DateField()),
                ('Business_hr_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.business_hr_management')),
                ('Employee', models.ManyToManyField(to='hr_management.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('Issue_Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Staff_issue', models.TextField()),
                ('Date', models.DateField()),
                ('Disciplinary_Action', models.TextField()),
                ('Action_Taken', models.TextField()),
                ('Business_hr_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.business_hr_management')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('Complain_Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Staff_issue', models.TextField()),
                ('Date', models.DateField()),
                ('Disciplinary_Action', models.TextField()),
                ('Action_Taken', models.TextField()),
                ('Business_hr_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.business_hr_management')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('Communication_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Message', models.TextField()),
                ('From', models.TextField()),
                ('To', models.TextField()),
                ('Business_hr_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.business_hr_management')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.employee')),
            ],
        ),
    ]
